steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.gateway
      - --tag
      - gcr.io/$PROJECT_ID/shivvr-gateway:$BUILD_ID
      - .
images:
  - gcr.io/$PROJECT_ID/shivvr-gateway:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY
